# Generated by Django 3.2 on 2021-05-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyconversiondetail',
            name='FinalOutput',
        ),
    ]
